### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by canbican** [canbican/ad-change-pass#1]
For a password of Ilovecake:) , I'd expect that to be set.
Instead, I get Ilovecake:\29 as the bracket doesn't seem to be encoded correctly.

**Comment by fgunger** [comment]
An option should be _not_ to "ldapescape" the password since they are escaped later on in the code (converting them to UTF-16). My perception is that special characters such as ) * etc in the passwords does not imply a risk of injection in the code.

**Comment by canbican** [comment]
Exactly. I just didn't have the time and motivation for a one-liner change :) If you have already changed it please send a pull request - I'll more than appreciate it.

**Comment by canbican** [comment]
Thank you very much for the pull request, it works as it should be now.
