### ISSUE TITLE
After a successful password change, can change other passwords at will

### ISSUE THREAD

**Issue by maarbu** [canbican/ad-change-pass#7]
It appears that global $ldap_connection hold it's value for the whole php session.  I would suggest adding close_ldap_connection at the end of index.php   This works for me.

**Comment by maarbu** [comment]
After further troubleshooting, the close_ldap_connection didn't help. After a successful password change, you can change the password of the same user back to the previous password by entering the previous password in all three password blanks.  It appears that it doesn't fully check the password the second time.

**Comment by canbican** [comment]
Thanks for the bug report and troubleshooting. Do you have any patches to merge?
