### ISSUE TITLE
ldap_get_entries() in functions.php returns lower-case attributes

### ISSUE THREAD

**Issue by maglub** [canbican/ad-change-pass#8]
In functions.php, line 76, I had to do the following change:

Was:

```
      $isLocked = $info[0]["lockoutTime"];
```

My environment:

```
      $isLocked = $info[0]["lockouttime"][0];
```

Apparently, ldap_get_entries() returns lower-case attributes (also according to the php5-ldap documentation), and in my AD environment (Windows 2012 server), lockouttime is an array of one element.

Not sure if this is the case in your environment.

**Comment by canbican** [comment]
It's curious that it has worked before, I guess this change in ldap_get_entries is introduced later. Having an array there also makes me wonder if there are cases where one can see more than one entry.

I don't have access to a Windows 2012 ad environment to verify. Furthermore, I don't have access to other versions to verify we don't break things :) It may be implemented as a configurable behaviour maybe.

**Comment by maglub** [comment]
In my environment, running on Ubuntu 14, same behavior on Mac OSX, I am looking at three attributes:

* pwdlastset (will be 0 if the user has to change the password at next login)
* badpwdcount
* lockouttime (will be 0 as long as the user is not locked out)

For example:

```
	  function getUserInfo($user){
	      global $config;
	      global $ldap_connection;
	      get_ldap_connection($config['username'],$config['password']);
	      if ($ldap_connection) {
	        $filter="(sAMAccountName=$user)";
	        $result = ldap_search($ldap_connection,$config['domain_dn'],$filter);
	        ldap_sort($ldap_connection,$result,"sn");
	        $info = ldap_get_entries($ldap_connection, $result);

		    $isLocked = $info[0]["lockouttime"][0];
			foreach(array("badpwdcount", "lockouttime", "pwdlastset") as $key){
				print "key: {$key} => ";
					print_r($info[0][$key]);
			}			
		}
		
		return $info;
	  }
```

The output of this is:

```
key: badpwdcount => Array
(
    [count] => 1
    [0] => 0
)
key: lockouttime => Array
(
    [count] => 1
    [0] => 0
)
key: pwdlastset => Array
(
    [count] => 1
    [0] => 130867080341935245
)
```

I got curious, so I double checked the documentation (http://php.net/manual/en/function.ldap-get-entries.php), which confirms this.

```
The structure of the array is as follows. The attribute index is converted to lowercase. (Attributes are case-insensitive for directory servers, but not when used as array indices.)
...
return_value[i]["attribute"]["count"] = number of values for attribute in ith entry
return_value[i]["attribute"][j] = jth value of attribute in ith entry
```

**Comment by canbican** [comment]
I'll be more than happy to accept a pull request or a patch :) Maybe then I can setup an Azure (looks like it's free for testing purposes) AD for testing.
